// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0--rc1
// source: coinbase.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Coinbase match message -- a trade execution
type CoinbaseMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType    string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // always "match"
	TradeId      string                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`       // exchange-generated trade identifier
	ProductId    string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // trading pair e.g., "BTC-USDT"
	Size         float64                `protobuf:"fixed64,4,opt,name=size,proto3" json:"size,omitempty"`                          // amount traded
	Price        float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                        // execution price
	Time         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`                            // trade time
	MakerOrderId string                 `protobuf:"bytes,7,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId string                 `protobuf:"bytes,8,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
}

func (x *CoinbaseMatch) Reset() {
	*x = CoinbaseMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coinbase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinbaseMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinbaseMatch) ProtoMessage() {}

func (x *CoinbaseMatch) ProtoReflect() protoreflect.Message {
	mi := &file_coinbase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinbaseMatch.ProtoReflect.Descriptor instead.
func (*CoinbaseMatch) Descriptor() ([]byte, []int) {
	return file_coinbase_proto_rawDescGZIP(), []int{0}
}

func (x *CoinbaseMatch) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CoinbaseMatch) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *CoinbaseMatch) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CoinbaseMatch) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CoinbaseMatch) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CoinbaseMatch) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CoinbaseMatch) GetMakerOrderId() string {
	if x != nil {
		return x.MakerOrderId
	}
	return ""
}

func (x *CoinbaseMatch) GetTakerOrderId() string {
	if x != nil {
		return x.TakerOrderId
	}
	return ""
}

// Wrapper tying raw Coinbase payload to canonical model
type CoinbaseMarketData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw       *CoinbaseMatch `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Canonical *MarketData    `protobuf:"bytes,2,opt,name=canonical,proto3" json:"canonical,omitempty"` // canonical.symbol = uppercase(remove "-" from raw.product_id)
}

func (x *CoinbaseMarketData) Reset() {
	*x = CoinbaseMarketData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coinbase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinbaseMarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinbaseMarketData) ProtoMessage() {}

func (x *CoinbaseMarketData) ProtoReflect() protoreflect.Message {
	mi := &file_coinbase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinbaseMarketData.ProtoReflect.Descriptor instead.
func (*CoinbaseMarketData) Descriptor() ([]byte, []int) {
	return file_coinbase_proto_rawDescGZIP(), []int{1}
}

func (x *CoinbaseMarketData) GetRaw() *CoinbaseMatch {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *CoinbaseMarketData) GetCanonical() *MarketData {
	if x != nil {
		return x.Canonical
	}
	return nil
}

var File_coinbase_proto protoreflect.FileDescriptor

var file_coinbase_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x0b, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x69,
	0x6e, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x6b,
	0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x12, 0x43, 0x6f, 0x69,
	0x6e, 0x62, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x29, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63,
	0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x61,
	0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x42, 0x10, 0x5a, 0x0e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x3b, 0x63, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coinbase_proto_rawDescOnce sync.Once
	file_coinbase_proto_rawDescData = file_coinbase_proto_rawDesc
)

func file_coinbase_proto_rawDescGZIP() []byte {
	file_coinbase_proto_rawDescOnce.Do(func() {
		file_coinbase_proto_rawDescData = protoimpl.X.CompressGZIP(file_coinbase_proto_rawDescData)
	})
	return file_coinbase_proto_rawDescData
}

var file_coinbase_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coinbase_proto_goTypes = []interface{}{
	(*CoinbaseMatch)(nil),         // 0: coinbase.CoinbaseMatch
	(*CoinbaseMarketData)(nil),    // 1: coinbase.CoinbaseMarketData
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*MarketData)(nil),            // 3: market.MarketData
}
var file_coinbase_proto_depIdxs = []int32{
	2, // 0: coinbase.CoinbaseMatch.time:type_name -> google.protobuf.Timestamp
	0, // 1: coinbase.CoinbaseMarketData.raw:type_name -> coinbase.CoinbaseMatch
	3, // 2: coinbase.CoinbaseMarketData.canonical:type_name -> market.MarketData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coinbase_proto_init() }
func file_coinbase_proto_init() {
	if File_coinbase_proto != nil {
		return
	}
	file_trade_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_coinbase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinbaseMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coinbase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinbaseMarketData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coinbase_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coinbase_proto_goTypes,
		DependencyIndexes: file_coinbase_proto_depIdxs,
		MessageInfos:      file_coinbase_proto_msgTypes,
	}.Build()
	File_coinbase_proto = out.File
	file_coinbase_proto_rawDesc = nil
	file_coinbase_proto_goTypes = nil
	file_coinbase_proto_depIdxs = nil
}
