---
# 1) Binance listener
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-go-md-listener-binance
  namespace: market-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-go-md-listener-binance
  template:
    metadata:
      labels:
        app: poc-go-md-listener-binance
    spec:
      containers:
        - name: poc-go-md-listener
          image: 512979937293.dkr.ecr.us-east-1.amazonaws.com/poc-go-md-listener:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: EXCHANGE
              value: "BINANCE"
            - name: SYMBOLS
              value: "BTCUSDC,XRPUSDT,ETHUSDT,USDTUSD,BTCUSDT,XLMUSDT,DOGEUSDT,SOLUSDT,ADAUSDT,HBARUSDT"
---
# 2) Coinbase listener
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-go-md-listener-coinbase
  namespace: market-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-go-md-listener-coinbase
  template:
    metadata:
      labels:
        app: poc-go-md-listener-coinbase
    spec:
      containers:
        - name: poc-go-md-listener
          image: 512979937293.dkr.ecr.us-east-1.amazonaws.com/poc-go-md-listener:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: EXCHANGE
              value: "COINBASE"
            - name: SYMBOLS
              value: "BTC-USD,XRP-USD,ETH-USD,XLM-USD,SOL-USD,DOGE-USD,BONK-USD,SUI-USD,ADA-USD,HBAR-USD"
---
# 3) Kraken listener
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-go-md-listener-kraken
  namespace: market-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-go-md-listener-kraken
  template:
    metadata:
      labels:
        app: poc-go-md-listener-kraken
    spec:
      containers:
        - name: poc-go-md-listener
          image: 512979937293.dkr.ecr.us-east-1.amazonaws.com/poc-go-md-listener:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: EXCHANGE
              value: "KRAKEN"
            - name: SYMBOLS
              value: "USDT/USD,XRP/USDT,ETH/USDT,USDC/USD,DOGE/USD,BTC/USD,SOL/USD,ADA/USD,LTC/USD,XLM/USD"